- platform: template
  switches:
    livebox:
      friendly_name: 'Livebox'
      value_template: "{{ is_state('media_player.livebox_tv', 'playing') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.livebox_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.livebox_tv