- platform: template
  switches:
    tv_samsung:
      friendly_name: 'TV Salon'
      value_template: "{{ is_state('media_player.tv_salon', 'on') }}"
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.tv_salon
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.tv_salon