- platform: yr
  monitored_conditions:
    - symbol
    - temperature
    - precipitation
    - windSpeed
    - windDirection
    - humidity
    - cloudiness
    - fog
    - pressure
    #- dewpointTemperature
