sensor:
  - platform: cryptocompare
    currency: XMR
    display_currency: EUR
  - platform: cryptocompare
    currency: XMR
    display_currency: USD
  - platform: cryptocompare
    currency: XMR
    display_currency: BTC
    display_round: 7
