sensor:
  - platform: cryptocompare
    currency: XMR
    display_currency: EUR
  - platform: cryptocompare
    currency: XMR
    display_currency: USD
  - platform: cryptocompare
    currency: XMR
    display_currency: BTC
    display_round: 7
  - platform: cryptonodepool
    pool_address: !secret first_pool_address
    wallet_address: !secret first_wallet_address
    pool_name: !secret first_pool_name
