sensor:
  # Date and time
  - platform: time_date
    display_options:
      - 'date_time'
      # - 'time'
      #- 'date_time'
      # - 'date'
      #- 'date_time'
      #- 'time_date'
      #- 'time_utc'
      #- 'beat'
