sensor:
  - platform: synologydsm
    host: !secret synology1_host
    username: !secret synology1_username
    password: !secret synology1_password
    monitored_conditions:
      - cpu_total_load
      - memory_real_usage
      - network_up
      - network_down
      - disk_smart_status
      - disk_status
      - disk_temp
      - volume_status
      - volume_percentage_used